In [1]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [43]:
def perp(x, a):
    a = a.reshape(-1,1)
    x2 = x.reshape(list(x.shape) + [1])
    return np.exp(np.abs((x - x2) * np.abs(x - x2))/(-2*a*a))/\
    (np.sum(np.exp((np.abs(x - x2) * np.abs(x - x2))/(-2*a*a)),0)-1)

In [46]:
perp(c, a)[1][1]

array([ 0.2963333 ,  0.37089554,  0.45279116,  0.61083568,  2.67062254])

In [ ]:
def tSNE(x, fc perp, t, r, a):
    p = fc(x,a)
    p2 = (p - p.T)/2*len(x)

In [42]:
a = np.arange(1,6)
b = np.arange(1,6)
c = a-b.reshape(-1,1)
print(c,np.ones_like(c)/a)

[[ 0  1  2  3  4]
 [-1  0  1  2  3]
 [-2 -1  0  1  2]
 [-3 -2 -1  0  1]
 [-4 -3 -2 -1  0]] [[ 1.          0.5         0.33333333  0.25        0.2       ]
 [ 1.          0.5         0.33333333  0.25        0.2       ]
 [ 1.          0.5         0.33333333  0.25        0.2       ]
 [ 1.          0.5         0.33333333  0.25        0.2       ]
 [ 1.          0.5         0.33333333  0.25        0.2       ]]


In [29]:
c.shape

(5, 5, 1)

In [33]:
list(c.shape)+[1]

[5, 5, 1, 1]

In [52]:
c = c[:,:4]
c

array([[ 0,  1,  2,  3],
       [-1,  0,  1,  2],
       [-2, -1,  0,  1],
       [-3, -2, -1,  0],
       [-4, -3, -2, -1]])

In [53]:
len(c)

5